# Type stubs for services.ai_agent
from typing import Any, Dict, List, Optional

def start_ai_conversation() -> Dict[str, Any]: ...
def process_ai_message(message: str, context_updates: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...
def reset_ai_conversation() -> Dict[str, Any]: ...
def get_ai_capabilities() -> List[str]: ...
def get_ai_context() -> Dict[str, Any]: ...
