# Type stubs for services.mcp_integration
from typing import Any, Dict, Optional

class MCPIntegrationService:
    def __init__(self) -> None: ...
    servers: Dict[str, Any]
    clients: Dict[str, Any]

class SATMCPIntegration:
    def __init__(self) -> None: ...

mcp_service: MCPIntegrationService
sat_mcp: SATMCPIntegration

def get_mcp_status() -> Dict[str, Any]: ...
def generate_intelligent_report(report_data: Dict[str, Any], report_type: str = "SAT") -> Dict[str, Any]: ...
def backup_report_with_mcp(report_id: str, report_data: Dict[str, Any]) -> Dict[str, Any]: ...
def schedule_reviews_with_mcp(report_id: str, review_schedule: Dict[str, Any]) -> Dict[str, Any]: ...
def fetch_standards_with_mcp(standard_type: str) -> Dict[str, Any]: ...
def analyze_project_with_mcp(project_id: str) -> Dict[str, Any]: ...