# Type stubs for flask_wtf
from typing import Any, Optional, Callable, Dict
from flask import Flask

class CSRFProtect:
    def __init__(self, app: Optional[Flask] = None) -> None: ...
    def init_app(self, app: Flask) -> None: ...

class CSRFError(Exception):
    def __init__(self, message: str) -> None: ...

def generate_csrf(secret_key: Optional[str] = None, token_key: Optional[str] = None) -> str: ...